### ISSUE TITLE
Not working in layouts

### ISSUE THREAD

**Issue by RoalSky** [vaadin-marcus/mouse-events#1]
The Addon works for Buttons Labels etc. but not for  Layouts.
Hope you can help me.Thanks

**Comment by RoalSky** [comment]
Could you please help me to find a way its working ?

**Comment by bseiller** [comment]
I've got a similar problem with all classes that extend AbstractSelect (i.e. ComboBox).
Any hint would be appreciated.

**Comment by RoalSky** [comment]
I used a workaround with css. Add the Layouts you want to hover over from the beginning just set them visibility hidden. After style:hover I mark it as visible.
Hope it is helping

**Comment by bseiller** [comment]
Thank you - what worked for me, at least in some cases was to explicitly add 
`DOM.sinkEvents(someElement, Event.ONMOUSEOVER | Event.ONMOUSEOUT);`
as described [here ](https://vaadin.com/forum/#!/thread/834207/834687)
in my _AbstractExtensionConnector_ implementation.
This seems necessary as not all widgets/gui elements react to those events by default.
But this does not work in all cases - e.g. the items in the popup menu of the ComboBox aren't a widget so no joy there.

**Comment by apm78** [comment]
I fixed it for layouts too. In the `MouseEventsConnector` I added the line `target.sinkEvents(Event.ONMOUSEOVER | Event.ONMOUSEOUT);`. My fork [here](https://github.com/apm78/mouse-events) contains the fix.

**Comment by marcushellberg** [comment]
Hi @apm78 - want to do a pull request so I can release a fixed version? Thanks!
